### ISSUE TITLE
update to Python 3.12

### ISSUE THREAD

**Issue by mpldr** [schorschii/Jabber4Linux#18]
Hi, during pip install, I get the following error. A quick research has yielded that this could be thanks to python 3.12 dropping that field (I am on 3.13)

```
Processing /home/moritz/Code/github.com/schorschii/Jabber4Linux
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting dnspython>=2.0 (from jabber4linux==0.7.0)
  Downloading dnspython-2.7.0-py3-none-any.whl.metadata (5.8 kB)
Requirement already satisfied: requests in /usr/lib/python3.13/site-packages (from jabber4linux==0.7.0) (2.32.4)
Requirement already satisfied: watchdog in /usr/lib/python3.13/site-packages (from jabber4linux==0.7.0) (6.0.0)
Requirement already satisfied: filelock in /usr/lib/python3.13/site-packages (from jabber4linux==0.7.0) (3.18.0)
Requirement already satisfied: cryptography>=2.5 in /usr/lib/python3.13/site-packages (from jabber4linux==0.7.0) (45.0.5)
Collecting asn1 (from jabber4linux==0.7.0)
  Downloading asn1-3.1.0-py2.py3-none-any.whl.metadata (7.4 kB)
Collecting pydbus (from jabber4linux==0.7.0)
  Downloading pydbus-0.6.0-py2.py3-none-any.whl.metadata (3.8 kB)
Collecting PyAudio==0.2.13 (from jabber4linux==0.7.0)
  Downloading PyAudio-0.2.13.tar.gz (46 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [32 lines of output]
      Traceback (most recent call last):
        File "/home/moritz/Code/github.com/schorschii/Jabber4Linux/venv/lib/python3.13/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 389, in <module>
          main()
          ~~~~^^
        File "/home/moritz/Code/github.com/schorschii/Jabber4Linux/venv/lib/python3.13/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 373, in main
          json_out["return_val"] = hook(**hook_input["kwargs"])
                                   ~~~~^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/moritz/Code/github.com/schorschii/Jabber4Linux/venv/lib/python3.13/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 137, in get_requires_for_build_wheel
          backend = _build_backend()
        File "/home/moritz/Code/github.com/schorschii/Jabber4Linux/venv/lib/python3.13/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 70, in _build_backend
          obj = import_module(mod_path)
        File "/usr/lib/python3.13/importlib/__init__.py", line 88, in import_module
          return _bootstrap._gcd_import(name[level:], package, level)
                 ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
        File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
        File "<frozen importlib._bootstrap>", line 1310, in _find_and_load_unlocked
        File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
        File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
        File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
        File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
        File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
        File "<frozen importlib._bootstrap_external>", line 1026, in exec_module
        File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
        File "/tmp/pip-build-env-tieub3hr/overlay/lib/python3.13/site-packages/setuptools/__init__.py", line 16, in <module>
          import setuptools.version
        File "/tmp/pip-build-env-tieub3hr/overlay/lib/python3.13/site-packages/setuptools/version.py", line 1, in <module>
          import pkg_resources
        File "/tmp/pip-build-env-tieub3hr/overlay/lib/python3.13/site-packages/pkg_resources/__init__.py", line 2191, in <module>
          register_finder(pkgutil.ImpImporter, find_on_path)
                          ^^^^^^^^^^^^^^^^^^^
      AttributeError: module 'pkgutil' has no attribute 'ImpImporter'. Did you mean: 'zipimporter'?
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.

[notice] A new release of pip is available: 25.1.1 -> 25.2
[notice] To update, run: /home/moritz/Code/github.com/schorschii/Jabber4Linux/venv/bin/python -m pip install --upgrade pip
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

**Comment by schorschii** [comment]
Please check out the current master branch and tell us if it's working with Python >= 3.12.
